### PR TITLE
Precompile using babel before publishing

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull requests publishes a babel-ified version of `index.js` so this module can be used in old node versions that don't support ES6 stuff.

Also adds a dependency on `es6-promise` that will be a fallback when `global.Promise` is missing.

Refs https://github.com/electron-userland/electron-download/pull/30

### CODE REVIEW

**Comment by malept** [comment]
Ugh, I guess `build.js` needs to be blacklisted from `eslint`.

**Comment by kevinsawicki** [comment]
Looks like the build is failing because of the code climate token.

> No CODECLIMATE_REPO_TOKEN found. A CODECLIMATE_REPO_TOKEN must be specified as an environment variable.

**Comment by malept** [comment]
> Looks like the build is failing because of the code climate token.

Weird. (Mostly because master didn't fail.) Let me add that to Travis.

**Comment by malept** [comment]
OK, this is really weird. I set `CODECLIMATE_REPO_TOKEN` in the Travis UI and it didn't take?

**Comment by kevinsawicki** [comment]
> I set CODECLIMATE_REPO_TOKEN in the Travis UI and it didn't take?

Hmm, is it private? I don't think private env vars are available to pull requests.

**Comment by malept** [comment]
Do you mind allowing me access to that branch via that nifty new checkbox? I will try to mess with it when I get home.

**Comment by kevinsawicki** [comment]
> Do you mind allowing me access to that branch via that nifty new checkbox? I will try to mess with it when I get home.

Yup, should be enabled, feel free to push at will.

**Comment by kevinsawicki** [comment]
eslint only supports node 4+ so linting won't be possible on CIs using node 0.10 and 0.12

**Pull request merged**
