### PR TITLE
v1.x: Explicitly set default encoding in createHash()

### PR DESCRIPTION
**Pull request by addaleax**
Backport PR for https://github.com/malept/sumchecker/pull/5 (which does cherry-pick cleanly, btw)

### CODE REVIEW

**Comment by addaleax** [comment]
Awesome, thanks!

**Comment by addaleax** [comment]
@malept Hate to nag, but is there any chance this could go out in a release (and/or be picked up by electron-prebuilt in some other way) in the next couple of days?

**Comment by malept** [comment]
I haven't had access to the computer where I release sumchecker lately. I will try within the next couple of days.

**Comment by addaleax** [comment]
bump @malept 

And by the way, according to the `sha*sum` source code, the `binary`/`text` switch doesn’t refer to encodings but to whether to open the file in text mode or not (for e.g. Windows where text mode automatically translates between `\r\n` and `\n`). Node doesn’t actually support text mode at all; if it’s something that `sumchecker` should support, it needs to do that translation itself.

**Comment by malept** [comment]
Published 1.3.1 and 2.0.2. Sorry for the delay.

**Comment by addaleax** [comment]
@malept No problem! Thanks for maintaining awesome open source software! :heart:

**Pull request merged**
